[
   
    {
      "id": 3,
      "name": "Dr. Arun Saroha",
      "specialty": "Neurosurgeon",
      "designation": " Director",
      "hospital": "Max Super Specialty Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "29+",
      "image": "https://www.vaidam.com/sites/default/files/image-removebg-preview45-min.png",
      "path": "/doctors/dr-arun-saroha"
    },
    {
      "id": 4,
      "name": "Dr. Arup Ratan Dutta",
      "specialty": "Nephrologist",
      "designation": " Director",
      "hospital": "Fortis Hospital and Kidney Institute (Rash Behari Ave), Kolkata",
      "city": "Kolkata, India",
      "experience": "35+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._dutta-min.jpg",
      "path": "/doctors/dr-arup-ratan-dutta"
    },
    {
      "id": 5,
      "name": "Dr. Ashok Rajgopal",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Senior Consultant",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "50+",
      "image": "https://www.vaidam.com/sites/default/files/dr_ashok_rajgopal-min.png",
      "path": "/doctors/dr-ashok-rajgopal"
    },
    {
      "id": 6,
      "name": "Dr. Ashok Seth",
      "specialty": "Interventional Cardiologist",
      "designation": " Chairman",
      "hospital": "Fortis Escorts Heart Institute, New Delhi",
      "city": "New Delhi, India",
      "experience": "40+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr._ashok_seth.webp",
      "path": "/doctors/dr-ashok-seth"
    },
    {
      "id": 7,
      "name": "Dr. Balbir Singh",
      "specialty": "Interventional Cardiologist",
      "designation": " Chairman",
      "hospital": "Max Super Speciality Hospital, Saket, New Delhi",
      "city": "Gurgaon, India",
      "experience": "36+",
      "image": "https://www.vaidam.com/sites/default/files/dr-balbir-singh-medanta.jpg",
      "path": "/doctors/dr-balbir-singh"
    },
    {
      "id": 8,
      "name": "Dr. Harit Chaturvedi",
      "specialty": "Surgical Oncologist",
      "designation": " Chairman",
      "hospital": "Max Super Speciality Hospital, Patparganj, New Delhi",
      "city": "New Delhi, India",
      "experience": "38+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._harit_chaturvedi_-_surgical_oncologist-min.jpg",
      "path": "/doctors/dr-harit-chaturvedi"
    },
    {
      "id": 9,
      "name": "Dr. Hemant Bhartiya",
      "specialty": "Spine Surgeon",
      "designation": " Director",
      "hospital": "Fortis Escorts Hospital Jaipur",
      "city": "Jaipur, India",
      "experience": "30+",
      "image": "https://www.vaidam.com/sites/default/files/dr._hemant_bhartiya-min.jpg",
      "path": "/doctors/dr-hemant-bhartiya"
    },
    {
      "id": 10,
      "name": "Dr. N.C. Krishnamani",
      "specialty": "Interventional Cardiologist",
      "designation": " Senior Consultant",
      "hospital": "Fortis Hospital, Shalimar Bagh, New Delhi",
      "city": "New Delhi, India",
      "experience": "36+",
      "image": "https://www.vaidam.com/sites/default/files/dr._n.c._krishnamani_1.jpeg",
      "path": "/doctors/dr-nc-krishnamani"
    },
    {
      "id": 11,
      "name": "Dr. Manoj Kumar Goel",
      "specialty": "Pulmonologist",
      "designation": " Director",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "36+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr._manoj_kumar_goel-removebg-preview-min.webp",
      "path": "/doctors/dr-manoj-kumar-goel"
    },
    {
      "id": 12,
      "name": "Dr. Naresh Trehan",
      "specialty": "Cardiac Surgeon",
      "designation": " Chairman",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "56+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr._naresh_trehan-min.webp",
      "path": "/doctors/dr-naresh-trehan"
    },
    {
      "id": 13,
      "name": "Dr. Praveen Chandra",
      "specialty": "Interventional Cardiologist",
      "designation": " Chairman",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "38+",
      "image": "https://www.vaidam.com/sites/default/files/dr._praveen_chandra-removebg-preview-min.png",
      "path": "/doctors/dr-praveen-chandra"
    },
    {
      "id": 14,
      "name": "Dr. Praveen Gupta",
      "specialty": "Neurologist",
      "designation": " Senior Consultant",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "26+",
      "image": "https://www.vaidam.com/sites/default/files/dr_praveen_gupta.jpg",
      "path": "/doctors/dr-praveen-gupta"
    },
    {
      "id": 15,
      "name": "Dr. Rama Joshi",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Consultant",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "39+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr-rama-joshi-gynae-oncology-3.jpg",
      "path": "/doctors/dr-rama-joshi"
    },
    {
      "id": 16,
      "name": "Dr. Rana Patir",
      "specialty": "Neurosurgeon",
      "designation": " Director",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "32+",
      "image": "https://www.vaidam.com/sites/default/files/dr._rana_patir_1.jpg",
      "path": "/doctors/dr-rana-patir"
    },
    {
      "id": 17,
      "name": "Dr. Sandeep Nayak",
      "specialty": "Surgical Oncologist",
      "designation": " Director",
      "hospital": "Fortis Hospital, Bangalore (Bannerghatta Road)",
      "city": "Bangalore, India",
      "experience": "28+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._sandeep_nayak.jpg",
      "path": "/doctors/dr-sandeep-nayak"
    },
    {
      "id": 18,
      "name": "Dr. Shuvanan Ray",
      "specialty": "Interventional Cardiologist",
      "designation": " Director",
      "hospital": "Fortis Hospital (Anandapur) Kolkata",
      "city": "Kolkata, India",
      "experience": "23+",
      "image": "https://www.vaidam.com/sites/default/files/dr_shuvanan_low_rez-min.jpg",
      "path": "/doctors/dr-shuvanan-ray"
    },
    {
      "id": 19,
      "name": "Dr. Subhash Gupta",
      "specialty": "Liver Transplant Surgeon",
      "designation": " Chairman",
      "hospital": "Max Super Speciality Hospital, Saket, New Delhi",
      "city": "New Delhi, India",
      "experience": "38+",
      "image": "https://www.vaidam.com/sites/default/files/dr-subhash-gupta-liver-transplant-surgeon.jpg",
      "path": "/doctors/dr-subhash-gupta"
    },
    {
      "id": 20,
      "name": "Dr. C Vijay Bose",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Director",
      "hospital": "SIMS Hospital, Vadapalani, Chennai",
      "city": "Chennai, India",
      "experience": "36+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._c_vijay_bose-min.jpg",
      "path": "/doctors/dr-c-vijay-bose"
    },
    {
      "id": 21,
      "name": "Dr. Shyam Kishore Shrivastava",
      "specialty": "Radiation Oncologist",
      "designation": " Senior Consultant",
      "hospital": "Apollo Proton Cancer Centre, Chennai",
      "city": "Chennai, India",
      "experience": "49+",
      "image": "https://www.vaidam.com/sites/default/files/drshyam_kishore_shrivastava-min.jpg",
      "path": "/doctors/dr-shyam-kishore-shrivastava"
    },
    {
      "id": 22,
      "name": "Dr. Sandeep Attawar",
      "specialty": "Cardiac Surgeon",
      "designation": " Director",
      "hospital": "KIMS Hospital Kondapur, Hyderabad",
      "city": "Hyderabad, India",
      "experience": "33+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr_sandeep_attawar-min.webp",
      "path": "/doctors/dr-sandeep-attawar"
    },
    {
      "id": 23,
      "name": "Dr. Sandeep Attawar",
      "specialty": "Cardiac Surgeon",
      "designation": " Director",
      "hospital": "KIMS Hospital Kondapur, Hyderabad",
      "city": "Hyderabad, India",
      "experience": "33+",
      "image": "https://www.vaidam.com/sites/default/files/dr_sandeep_attawar-min.jpg",
      "path": "/doctors/dr-sandeep-attawar"
    },
    {
      "id": 24,
      "name": "Dr. Sanjay Sarup",
      "specialty": "Paediatric Orthopedecian",
      "designation": " Senior Consultant",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "32+",
      "image": "https://www.vaidam.com/sites/default/files/dr._sanjay_sarup-min.jpg",
      "path": "/doctors/dr-sanjay-sarup"
    },
    {
      "id": 25,
      "name": "Dr. Jatinder Bir Singh Jaggi",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Director",
      "hospital": "Max Super Specialty Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "31+",
      "image": "https://www.vaidam.com/sites/default/files/dr-jatinder-bir-singh-jaggi-arthroscopy-orthopedics.jpg",
      "path": "/doctors/dr-jatinder-bir-singh-jaggi"
    },
    {
      "id": 26,
      "name": "Dr. Rajeev Verma",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Chairman",
      "hospital": "Manipal Hospitals Dwarka, Delhi",
      "city": "New Delhi, India",
      "experience": "28+",
      "image": "https://www.vaidam.com/sites/default/files/dr._rajeev_vermaa-removebg-preview.png",
      "path": "/doctors/dr-rajeev-verma"
    },
    {
      "id": 27,
      "name": "Dr. Subhash Jangid",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Director",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "25+",
      "image": "https://www.vaidam.com/sites/default/files/subhashjangid-gurgaon-7c8d42.jpg",
      "path": "/doctors/dr-subhash-jangid"
    },
    {
      "id": 28,
      "name": "Dr. Ishwar Bohra",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Senior Consultant",
      "hospital": "BLK-Max Super Speciality Hospital Delhi",
      "city": "New Delhi, India",
      "experience": "24+",
      "image": "https://www.vaidam.com/sites/default/files/dr.ishwar_borah-min.jpg",
      "path": "/doctors/dr-ishwar-bohra"
    },
    {
      "id": 29,
      "name": "Dr. Vikram Barua Kaushik",
      "specialty": "Urologist",
      "designation": " Consultant",
      "hospital": "Manipal Hospital Formerly Columbia Asia, Palam Vihar, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "29+",
      "image": "https://www.vaidam.com/sites/default/files/dr._vikram_barua_kaushik-min.jpg",
      "path": "/doctors/dr-vikram-barua-kaushik"
    },
    {
      "id": 30,
      "name": "Dr. Z S Meharwal",
      "specialty": "Cardiac Surgeon",
      "designation": " Chairman",
      "hospital": "Fortis Escorts Heart Institute, New Delhi",
      "city": "New Delhi, India",
      "experience": "42+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr-z-s-meharwal_cardio-thorasic-vascular-surgery982956-min.webp",
      "path": "/doctors/dr-z-s-meharwal"
    },
    {
      "id": 31,
      "name": "Dr. Z S Meharwal",
      "specialty": "Cardiac Surgeon",
      "designation": " Chairman",
      "hospital": "Fortis Escorts Heart Institute, New Delhi",
      "city": "New Delhi, India",
      "experience": "42+",
      "image": "https://www.vaidam.com/sites/default/files/dr-z-s-meharwal_cardio-thorasic-vascular-surgery982956-min.jpg",
      "path": "/doctors/dr-z-s-meharwal"
    },
    {
      "id": 32,
      "name": "Dr. Yash Gulati",
      "specialty": "Spine and Pain Specialist",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "46+",
      "image": "https://www.vaidam.com/sites/default/files/dr.-yash-gulati-orthopedic-surgeon-compressor-min.jpg",
      "path": "/doctors/dr-yash-gulati"
    },
    {
      "id": 33,
      "name": "Dr. Y K Mishra",
      "specialty": "Cardiac Surgeon",
      "designation": " Chairman",
      "hospital": "Manipal Hospitals Dwarka, Delhi",
      "city": "New Delhi, India",
      "experience": "44+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr._y_k_mishra_1.webp",
      "path": "/doctors/dr-y-k-mishra"
    },
    {
      "id": 34,
      "name": "Dr. Vivekanandan Shanmugam",
      "specialty": "Liver Transplant Surgeon",
      "designation": " Senior Consultant",
      "hospital": "SIMS Hospital, Vadapalani, Chennai",
      "city": "Chennai, India",
      "experience": "21+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr-vivekanandan-shanmugam-min.jpg",
      "path": "/doctors/dr-vivekanandan-shanmugam"
    },
    {
      "id": 35,
      "name": "Dr. Vivek Vij",
      "specialty": "Liver Transplant Surgeon",
      "designation": " Chairman",
      "hospital": "Fortis Hospital, Noida",
      "city": "New Delhi, India",
      "experience": "27+",
      "image": "https://www.vaidam.com/sites/default/files/dr_vivek_vij.jpg",
      "path": "/doctors/dr-vivek-vij"
    },
    {
      "id": 36,
      "name": "Dr. Vivek Raj",
      "specialty": "Medical Gastroenterologist",
      "designation": " Director",
      "hospital": "Max Super Speciality Hospital, Saket, New Delhi",
      "city": "New Delhi, India",
      "experience": "43+",
      "image": "https://www.vaidam.com/sites/default/files/dr-vivek-raj-max.jpg",
      "path": "/doctors/dr-vivek-raj"
    },
    {
      "id": 37,
      "name": "Dr Vipul Gupta",
      "specialty": "Neurosurgeon",
      "designation": " Director",
      "hospital": "Paras Hospitals, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "29+",
      "image": "https://www.vaidam.com/sites/default/files/dr_vipul_gupta-min.jpg",
      "path": "/doctors/dr-vipul-gupta"
    },
    {
      "id": 38,
      "name": "Dr Vipul Gupta",
      "specialty": "Neurosurgeon",
      "designation": " Director",
      "hospital": "Paras Hospitals, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "29+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_vipul_gupta-min.jpg",
      "path": "/doctors/dr-vipul-gupta"
    },
    {
      "id": 39,
      "name": "Dr. Vinod Raina",
      "specialty": "Medical Oncologist",
      "designation": " Chairman",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "40+",
      "image": "https://www.vaidam.com/sites/default/files/dr._vinod_raina-min.png",
      "path": "/doctors/dr-vinod-raina"
    },
    {
      "id": 40,
      "name": "Dr. Vinod Kumar Nigam",
      "specialty": "General Surgeon",
      "designation": " Senior Consultant",
      "hospital": "Max Super Specialty Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "55+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr-vinod-kumar-nigam.jpg",
      "path": "/doctors/dr-vinod-kumar-nigam"
    },
    {
      "id": 41,
      "name": "Dr. Vineesh Mathur",
      "specialty": "Spine Surgeon",
      "designation": " Director",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "36+",
      "image": "https://www.vaidam.com/sites/default/files/dr._vineesh_mathur-removebg-preview-min.png",
      "path": "/doctors/dr-vineesh-mathur"
    },
    {
      "id": 42,
      "name": "Dr. Vikram Pratap Singh",
      "specialty": "Surgical Oncologist",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "50+",
      "image": "https://www.vaidam.com/sites/default/files/vikram_pratap_singh-min.jpg",
      "path": "/doctors/dr-vikram-pratap-singh"
    },
    {
      "id": 43,
      "name": "Dr Vikas Singhal",
      "specialty": "Obesity and Bariatric Surgeon",
      "designation": " Consultant",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "25+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_vikas_singhal-min.jpg",
      "path": "/doctors/dr-vikas-singhal"
    },
    {
      "id": 44,
      "name": "Dr. Vikas Dua",
      "specialty": "Pediatric Hematologist",
      "designation": " Director",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "22+",
      "image": "https://www.vaidam.com/sites/default/files/dr_vikas_dua-min.png",
      "path": "/doctors/dr-vikas-dua"
    },
    {
      "id": 45,
      "name": "Dr. Vijaya Rajakumari",
      "specialty": "Nephrologist",
      "designation": " Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "33+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._vijaya_rajakumari-min.jpg",
      "path": "/doctors/dr-vijaya-rajakumari"
    },
    {
      "id": 46,
      "name": "Dr. Vidyadhara S.",
      "specialty": "Spine Surgeon",
      "designation": " HOD",
      "hospital": "Manipal Hospital (Old Airport Road) Bangalore",
      "city": "Bangalore, India",
      "experience": "25+",
      "image": "https://www.vaidam.com/sites/default/files/dr._vidyadhara.jpg",
      "path": "/doctors/dr-vidyadhara-s"
    },
    {
      "id": 47,
      "name": "Dr. Vidur Jyoti",
      "specialty": "Advanced Laparoscopic, Minimal Access and Bariatric Surgeon",
      "designation": " Director",
      "hospital": "Max Super Specialty Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "45+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._vidur_jyoti-min.jpg",
      "path": "/doctors/dr-vidur-jyoti"
    },
    {
      "id": 48,
      "name": "Dr. Veena Bhat",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Director",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "48+",
      "image": "https://www.vaidam.com/sites/default/files/veena_bhat.jpg",
      "path": "/doctors/dr-veena-bhat"
    },
    {
      "id": 49,
      "name": "Dr. V. P. Singh",
      "specialty": "Neurosurgeon",
      "designation": " Chairman",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "36+",
      "image": "https://www.vaidam.com/sites/default/files/dr._v._p._singh-removebg-preview-min.png",
      "path": "/doctors/dr-v-p-singh"
    },
    {
      "id": 50,
      "name": "Dr. Umesh Gupta",
      "specialty": "Nephrologist",
      "designation": " Director",
      "hospital": "Aakash Healthcare Super Speciality Hospital, Dwarka, New Delhi",
      "city": "New Delhi, India",
      "experience": "30+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_umesh_gupta.jpg",
      "path": "/doctors/dr-umesh-gupta"
    },
    {
      "id": 51,
      "name": "Dr. Tushar Shah",
      "specialty": "Neurosurgeon",
      "designation": " Consultant",
      "hospital": "CIMS Hospital, Ahmedabad",
      "city": "Ahmedabad, India",
      "experience": "37+",
      "image": "https://www.vaidam.com/sites/default/files/dr._tushar_shah.jpg",
      "path": "/doctors/dr-tushar-shah"
    },
    {
      "id": 52,
      "name": "Dr. TPR Bharadwaj",
      "specialty": "Hematologist",
      "designation": " Consultant",
      "hospital": "Apollo Hospitals, Greams Road, Chennai",
      "city": "Chennai, India",
      "experience": "52+",
      "image": "https://www.vaidam.com/sites/default/files/tpr_bharadwaj_1.jpg",
      "path": "/doctors/dr-tpr-bharadwaj"
    },
    {
      "id": 53,
      "name": "Dr. T. S. Kler",
      "specialty": "Interventional Cardiologist",
      "designation": " Chairman",
      "hospital": "BLK-Max Super Speciality Hospital Delhi",
      "city": "New Delhi, India",
      "experience": "48+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr._t._s._kler-min.webp",
      "path": "/doctors/dr-t-s-kler"
    },
    {
      "id": 54,
      "name": "Dr. T. S. Kler",
      "specialty": "Electrophysiologist",
      "designation": " Chairman",
      "hospital": "BLK-Max Super Speciality Hospital Delhi",
      "city": "New Delhi, India",
      "experience": "48+",
      "image": "https://www.vaidam.com/sites/default/files/dr._t._s._kler-min.png",
      "path": "/doctors/dr-t-s-kler"
    },
    {
      "id": 55,
      "name": "Dr. Sushma Ved",
      "specialty": "Infertility Specialist",
      "designation": " Senior Consultant",
      "hospital": "Mediworld IVF Center and Fertility",
      "city": "New Delhi, India",
      "experience": "16+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_sushma_ved_embryologist_mediworld_fertility_centre_newdelhi.jpg",
      "path": "/doctors/dr-sushma-ved"
    },
    {
      "id": 56,
      "name": "Prof. Dr. Suresh H. Advani",
      "specialty": "Medical Oncologist",
      "designation": " Senior Consultant",
      "hospital": "Nanavati Super Specialty Hospital, Mumbai",
      "city": "Mumbai, India",
      "experience": "50+",
      "image": "https://www.vaidam.com/sites/default/files/prof._dr._suresh_h._advani-min.jpg",
      "path": "/doctors/prof-dr-suresh-h-advani"
    },
    {
      "id": 57,
      "name": "Dr. Suneeta Mittal",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Director",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "50+",
      "image": "https://www.vaidam.com/sites/default/files/dr-sunita-mittal_0.jpg",
      "path": "/doctors/dr-suneeta-mittal"
    },
    {
      "id": 58,
      "name": "Dr. Sumit Malhotra",
      "specialty": "Aesthetics and Plastic Surgeon",
      "designation": " Consultant",
      "hospital": NaN,
      "city": "Lucknow, India",
      "experience": "24+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_sumit_malhotra.png",
      "path": "/doctors/dr-sumit-malhotra"
    },
    {
      "id": 59,
      "name": "Dr. Sulbha Arora",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Director",
      "hospital": "NOVA IVI Fertility, Mumbai",
      "city": "Mumbai, India",
      "experience": "26+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr._sulbha_arora-min.webp",
      "path": "/doctors/dr-sulbha-arora"
    },
    {
      "id": 60,
      "name": "Dr. Sukhvinder Singh Saggu",
      "specialty": "Advanced Laparoscopic, Minimal Access and Bariatric Surgeon",
      "designation": " Consultant",
      "hospital": "CK Birla Hospital, Punjabi Bagh, New Delhi",
      "city": "New Delhi, India",
      "experience": "25+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._sukhvinder_singh_saggu_-_bariatric_and_laparoscopic_surgeon.jpg",
      "path": "/doctors/dr-sukhvinder-singh-saggu"
    },
    {
      "id": 61,
      "name": "Dr. Sujit Chaudhury",
      "specialty": "Medical Gastroenterologist",
      "designation": " Consultant",
      "hospital": "Manipal Hospitals Broadway Formerly AMRI Hospitals, Saltlake",
      "city": "Kolkata, India",
      "experience": "40+",
      "image": "https://www.vaidam.com/sites/default/files/dr._sujit_chaudhury-min.jpg",
      "path": "/doctors/dr-sujit-chaudhury"
    },
    {
      "id": 62,
      "name": "Dr. Sudhir Dubey",
      "specialty": "Neurosurgeon",
      "designation": " Chairman",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "30+",
      "image": "https://www.vaidam.com/sites/default/files/dr._sudhir_dubey-removebg-preview-min.png",
      "path": "/doctors/dr-sudhir-dubey"
    },
    {
      "id": 63,
      "name": "Dr. Sudhir Dubey",
      "specialty": "Neurosurgeon",
      "designation": " Chairman",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "30+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._sudhir_dubey-removebg-preview-min.png",
      "path": "/doctors/dr-sudhir-dubey"
    },
    {
      "id": 64,
      "name": "Dr. Subodh Chandra Pande",
      "specialty": "Radiation Oncologist",
      "designation": " Consultant",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "10+",
      "image": "https://www.vaidam.com/sites/default/files/dr-subhash-chandra-pande-radiation-oncology.jpg",
      "path": "/doctors/dr-subodh-chandra-pande"
    },
    {
      "id": 65,
      "name": "Dr. Srinivasa Prasad B V",
      "specialty": "Interventional Cardiologist",
      "designation": " Consultant",
      "hospital": "Fortis Hospital, Bangalore (Bannerghatta Road)",
      "city": "Bangalore, India",
      "experience": "24+",
      "image": "https://www.vaidam.com/sites/default/files/dr._srinivasa_prasad_b_v.jpg",
      "path": "/doctors/dr-srinivasa-prasad-b-v"
    },
    {
      "id": 66,
      "name": "Dr. Srikanth M",
      "specialty": "Hematologist",
      "designation": " Consultant",
      "hospital": "Apollo Hospitals, Greams Road, Chennai",
      "city": "Chennai, India",
      "experience": "29+",
      "image": "https://www.vaidam.com/sites/default/files/dr._srikanth_m-min.jpg",
      "path": "/doctors/dr-srikanth-m"
    },
    {
      "id": 67,
      "name": "Dr. Smita Mishra",
      "specialty": "Pediatric Cardiologist",
      "designation": " HOD",
      "hospital": "Manipal Hospitals Dwarka, Delhi",
      "city": "New Delhi, India",
      "experience": "41+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr-smita-mishra-consultant-and-hod-paediatrics-cardiology-min.jpeg",
      "path": "/doctors/dr-smita-mishra"
    },
    {
      "id": 68,
      "name": "Dr. Siddhartha Ghosh",
      "specialty": "Neurosurgeon",
      "designation": " Senior Consultant",
      "hospital": "Apollo Proton Cancer Centre, Chennai",
      "city": "Chennai, India",
      "experience": "40+",
      "image": "https://www.vaidam.com/sites/default/files/6_2.jpg",
      "path": "/doctors/dr-siddhartha-ghosh"
    },
    {
      "id": 69,
      "name": "Dr. Shilpa Saple",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Consultant",
      "hospital": "ART Fertility Clinics, Mumbai",
      "city": "Mumbai, India",
      "experience": "25+",
      "image": "https://d1ea147o02h74h.cloudfront.net/shilpasaple-mumbai-572db3_1-min.png",
      "path": "/doctors/dr-shilpa-saple"
    },
    {
      "id": 70,
      "name": "Dr. Shashidhar",
      "specialty": "Interventional Cardiologist",
      "designation": " Consultant",
      "hospital": "Fortis Hospital, Bangalore (Bannerghatta Road)",
      "city": "Bangalore, India",
      "experience": "34+",
      "image": "https://www.vaidam.com/sites/default/files/dr._shashidhar.jpg",
      "path": "/doctors/dr-shashidhar"
    },
    {
      "id": 71,
      "name": "Dr. Sharad Sheth",
      "specialty": "Nephrologist",
      "designation": " Head of Department",
      "hospital": "Kokilaben Dhirubhai Ambani Hospital, Mumbai",
      "city": "Mumbai, India",
      "experience": "49+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._sharad_sheth-min.png",
      "path": "/doctors/dr-sharad-sheth"
    },
    {
      "id": 72,
      "name": "Dr. Shakti Bhan Khanna",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "10+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/1231.webp",
      "path": "/doctors/dr-shakti-bhan-khanna"
    },
    {
      "id": 73,
      "name": "Dr. Sejal Shah",
      "specialty": "Pediatric Cardiologist",
      "designation": " Senior Consultant",
      "hospital": "Rainbow Children's Hospital & BirthRight by Rainbow, Bangalore",
      "city": "Bangalore, India",
      "experience": "28+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr.sejal_shah.jpg",
      "path": "/doctors/dr-sejal-shah"
    },
    {
      "id": 74,
      "name": "Dr. Vineet Bhushan Gupta",
      "specialty": "Paediatrician",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "28+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._vineet_bhushan_gupta_0.jpg",
      "path": "/doctors/dr-vineet-bhushan-gupta"
    },
    {
      "id": 75,
      "name": "Dr Saurabh Rawall",
      "specialty": "Spine Surgeon",
      "designation": " Consultant",
      "hospital": NaN,
      "city": "Noida, India",
      "experience": "18+",
      "image": "https://www.vaidam.com/sites/default/files/dr_saurabh_rawall-min.jpg",
      "path": "/doctors/dr-saurabh-rawall"
    },
    {
      "id": 76,
      "name": "Dr. Satya Gupta",
      "specialty": "Interventional Cardiologist",
      "designation": " Consultant",
      "hospital": "CIMS Hospital, Ahmedabad",
      "city": "Ahmedabad, India",
      "experience": "27+",
      "image": "https://www.vaidam.com/sites/default/files/dr._satya_gupta.jpg",
      "path": "/doctors/dr-satya-gupta"
    },
    {
      "id": 77,
      "name": "Dr. Satish N",
      "specialty": "General Surgeon",
      "designation": " Senior Consultant",
      "hospital": "Manipal Hospital Formerly Columbia Asia Referral Hospital, Bangalore (Yeshwanthpur)",
      "city": "Bangalore, India",
      "experience": "32+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_satish_n-removebg-preview-min.png",
      "path": "/doctors/dr-satish-n"
    },
    {
      "id": 78,
      "name": "Dr. Sanjay Verma",
      "specialty": "Advanced Laparoscopic, Minimal Access and Bariatric Surgeon",
      "designation": " Director",
      "hospital": "Fortis Escorts Heart Institute, New Delhi",
      "city": "New Delhi, India",
      "experience": "30+",
      "image": "https://www.vaidam.com/sites/default/files/dr._sanjay_verma.jpg",
      "path": "/doctors/dr-sanjay-verma"
    },
    {
      "id": 79,
      "name": "Dr. Sanjay Gogoi",
      "specialty": "Urologist and Renal Transplant Specialist",
      "designation": " Director",
      "hospital": NaN,
      "city": "New Delhi, India",
      "experience": "25+",
      "image": "https://www.vaidam.com/sites/default/files/dr._sanjay_gogoi-min.jpg",
      "path": "/doctors/dr-sanjay-gogoi"
    },
    {
      "id": 80,
      "name": "Dr. Sandip Shah",
      "specialty": "Neurosurgeon",
      "designation": " Consultant",
      "hospital": "CIMS Hospital, Ahmedabad",
      "city": "Ahmedabad, India",
      "experience": "19+",
      "image": "https://www.vaidam.com/sites/default/files/dr-sandip-shah-1.jpg",
      "path": "/doctors/dr-sandip-shah"
    },
    {
      "id": 81,
      "name": "Dr. Sandeep Vaishya",
      "specialty": "Neurosurgeon",
      "designation": " Director",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "36+",
      "image": "https://www.vaidam.com/sites/default/files/dr._sandeep_vaishya_0-min.jpg",
      "path": "/doctors/dr-sandeep-vaishya"
    },
    {
      "id": 82,
      "name": "Dr. Sameer Kaul",
      "specialty": "Medical Oncologist",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "30+",
      "image": "https://www.vaidam.com/sites/default/files/dr._kaul-min.jpg",
      "path": "/doctors/dr-sameer-kaul"
    },
    {
      "id": 83,
      "name": "Dr. Salil Jain",
      "specialty": "Nephrologist",
      "designation": " Director",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "40+",
      "image": "https://www.vaidam.com/sites/default/files/dr._salil_jain-min.png",
      "path": "/doctors/dr-salil-jain"
    },
    {
      "id": 84,
      "name": "Dr. Saket Goel",
      "specialty": "Colo-Rectal Surgeon",
      "designation": " Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "30+",
      "image": "https://www.vaidam.com/sites/default/files/dr_saket_goel.jpg",
      "path": "/doctors/dr-saket-goel"
    },
    {
      "id": 85,
      "name": "Dr. Sajan K Hegde",
      "specialty": "Spine Surgeon",
      "designation": " Senior Consultant",
      "hospital": "Apollo Hospitals, Greams Road, Chennai",
      "city": "Chennai, India",
      "experience": "44+",
      "image": "https://www.vaidam.com/sites/default/files/dr._sajan-min.jpg",
      "path": "/doctors/dr-sajan-k-hegde"
    },
    {
      "id": 86,
      "name": "Dr. Sabhyata Gupta",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Director",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "38+",
      "image": "https://www.vaidam.com/sites/default/files/dr._sabhyata_gupta.jpg",
      "path": "/doctors/dr-sabhyata-gupta"
    },
    {
      "id": 87,
      "name": "Dr. S K Rajan",
      "specialty": "Spine Surgeon",
      "designation": " HOD",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "22+",
      "image": "https://www.vaidam.com/sites/default/files/image-removebg-preview70-min.png",
      "path": "/doctors/dr-s-k-rajan"
    },
    {
      "id": 88,
      "name": "Dr. S. V. Kotwal",
      "specialty": "Urologist",
      "designation": " Head of Department",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "47+",
      "image": "https://www.vaidam.com/sites/default/files/image-removebg-preview74-min.png",
      "path": "/doctors/dr-s-v-kotwal"
    },
    {
      "id": 89,
      "name": "Dr. Robert Mao",
      "specialty": "Interventional Cardiologist",
      "designation": " Consultant",
      "hospital": "Apollo Hospitals, Greams Road, Chennai",
      "city": "Chennai, India",
      "experience": "53+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr-robert-mao-cardiologist.webp",
      "path": "/doctors/dr-robert-mao"
    },
    {
      "id": 90,
      "name": "Dr. Robert Mao",
      "specialty": "Interventional Cardiologist",
      "designation": " Consultant",
      "hospital": "Apollo Hospitals, Greams Road, Chennai",
      "city": "Chennai, India",
      "experience": "53+",
      "image": "https://www.vaidam.com/sites/default/files/dr-robert-mao-cardiologist.jpg",
      "path": "/doctors/dr-robert-mao"
    },
    {
      "id": 91,
      "name": "Dr. Robert Coelho",
      "specialty": "Pediatric Cardiac Surgeon",
      "designation": " Director",
      "hospital": "MIOT International, Chennai",
      "city": "Chennai, India",
      "experience": "34+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._coelho.images-min.jpeg",
      "path": "/doctors/dr-robert-coelho"
    },
    {
      "id": 92,
      "name": "Dr. Revathi Raj",
      "specialty": "Pediatric Hematologist",
      "designation": " Senior Consultant",
      "hospital": "Apollo Cancer Hospital, Chennai",
      "city": "Chennai, India",
      "experience": "34+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr-revathi-raj-min.jpg",
      "path": "/doctors/dr-revathi-raj"
    },
    {
      "id": 93,
      "name": "Dr. Renu Raina Sehgal",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Senior Consultant",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "28+",
      "image": "https://www.vaidam.com/sites/default/files/dr._renu_raina_sehgal-min.jpg",
      "path": "/doctors/dr-renu-raina-sehgal"
    },
    {
      "id": 94,
      "name": "Dr. Ravi Bhatia",
      "specialty": "Neurosurgeon",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "55+",
      "image": "https://www.vaidam.com/sites/default/files/dr._ravi_bhatia-min.jpg",
      "path": "/doctors/dr-ravi-bhatia"
    },
    {
      "id": 95,
      "name": "Dr. Ramya Mishra",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Senior Consultant",
      "hospital": "Apollo Fertility Center, Lajpat Nagar",
      "city": "New Delhi, India",
      "experience": "16+",
      "image": "https://www.vaidam.com/sites/default/files/dr_ramya_mishra.jpg",
      "path": "/doctors/dr-ramya-mishra"
    },
    {
      "id": 96,
      "name": "Dr. Ramesh Sarin",
      "specialty": "Surgical Oncologist",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "10+",
      "image": "https://www.vaidam.com/sites/default/files/dr_ramesh_sarin.jpg",
      "path": "/doctors/dr-ramesh-sarin"
    },
    {
      "id": 97,
      "name": "Dr. Ramesh S Bilimagga",
      "specialty": "Radiation Oncologist",
      "designation": " Senior Consultant",
      "hospital": "HCG Cancer Centre, Bangalore",
      "city": "Bangalore, India",
      "experience": "43+",
      "image": "https://www.vaidam.com/sites/default/files/dr_ramesh_billimagga-radiationoncologist-hcgbangalore-min.jpg",
      "path": "/doctors/dr-ramesh-s-bilimagga"
    },
    {
      "id": 98,
      "name": "Dr. Ramen Goel",
      "specialty": "General Surgeon",
      "designation": " Consultant",
      "hospital": "Wockhardt Hospital, Mumbai",
      "city": "Mumbai, India",
      "experience": "39+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._ramen_goel.jpg",
      "path": "/doctors/dr-ramen-goel"
    },
    {
      "id": 99,
      "name": "Dr. Ramani Narasimhan",
      "specialty": "Paediatric Orthopedecian",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "39+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._ramani_narasimhan-removebg-preview.png",
      "path": "/doctors/dr-ramani-narasimhan"
    },
    {
      "id": 100,
      "name": "Dr. Rakesh Agarwal",
      "specialty": "Neurologist",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "44+",
      "image": "https://www.vaidam.com/sites/default/files/dr._rakesh_agarwal-min.png",
      "path": "/doctors/dr-rakesh-agarwal"
    },
    {
      "id": 101,
      "name": "Dr Raju Vyas",
      "specialty": "Cardiac Surgeon",
      "designation": " Director",
      "hospital": "Fortis Hospital, Shalimar Bagh, New Delhi",
      "city": "New Delhi, India",
      "experience": "36+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr_raju_vyas_cleanup-min.webp",
      "path": "/doctors/dr-raju-vyas"
    },
    {
      "id": 102,
      "name": "Dr Raju Vyas",
      "specialty": "Cardiac Surgeon",
      "designation": " Director",
      "hospital": "Fortis Hospital, Shalimar Bagh, New Delhi",
      "city": "New Delhi, India",
      "experience": "36+",
      "image": "https://www.vaidam.com/sites/default/files/dr_raju_vyas_cleanup-min.jpg",
      "path": "/doctors/dr-raju-vyas"
    },
    {
      "id": 103,
      "name": "Dr Rajinder Yadav",
      "specialty": "Urologist",
      "designation": " Director",
      "hospital": "Fortis Hospital, Shalimar Bagh, New Delhi",
      "city": "New Delhi, India",
      "experience": "51+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_rajinder_yadav-min.jpg",
      "path": "/doctors/dr-rajinder-yadav"
    },
    {
      "id": 104,
      "name": "Dr. Rajesh Sharma",
      "specialty": "Pediatric Cardiac Surgeon",
      "designation": " Program Director",
      "hospital": "Marengo Asia Hospitals Formerly QRG Health City, Faridabad",
      "city": "New Delhi, India",
      "experience": "32+",
      "image": "https://www.vaidam.com/sites/default/files/dr._rajesh_sharma-min.jpg",
      "path": "/doctors/dr-rajesh-sharma"
    },
    {
      "id": 105,
      "name": "Dr. Rajesh Kumar Verma",
      "specialty": "Spine Surgeon",
      "designation": " Director",
      "hospital": "Sanar International Hospital",
      "city": "Gurgaon, India",
      "experience": "27+",
      "image": "https://www.vaidam.com/sites/default/files/dr._rajesh-min_0.jpg",
      "path": "/doctors/dr-rajesh-kumar-verma"
    },
    {
      "id": 106,
      "name": "Dr. Rajesh Kumar Verma",
      "specialty": "Spine Surgeon",
      "designation": " Director",
      "hospital": "Sanar International Hospital",
      "city": "Gurgaon, India",
      "experience": "27+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._rajesh-min_0.jpg",
      "path": "/doctors/dr-rajesh-kumar-verma"
    },
    {
      "id": 107,
      "name": "Dr. Rajesh Kapoor",
      "specialty": "Surgical Gastroenterologist",
      "designation": " Director",
      "hospital": "Jaypee Hospital, Noida",
      "city": "Noida, India",
      "experience": "42+",
      "image": "https://www.vaidam.com/sites/default/files/dr._rajesh-kapoor-min_0.jpg",
      "path": "/doctors/dr-rajesh-kapoor"
    },
    {
      "id": 108,
      "name": "Dr. Rajat Kumar Gupta",
      "specialty": "Pediatric Cardiologist",
      "designation": " Senior Consultant",
      "hospital": "Fortis Hospital, Mohali",
      "city": "Mohali, India",
      "experience": "15+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_rajat_1.jpg",
      "path": "/doctors/dr-rajat-kumar-gupta"
    },
    {
      "id": 109,
      "name": "Dr. Rajagopalan Krishnan",
      "specialty": "Spine Surgeon",
      "designation": " Senior Consultant",
      "hospital": NaN,
      "city": "New Delhi, India",
      "experience": "32+",
      "image": "https://www.vaidam.com/sites/default/files/image-removebg-preview46-min.png",
      "path": "/doctors/dr-rajagopalan-krishnan"
    },
    {
      "id": 110,
      "name": "Dr. Rajagopalan Krishnan",
      "specialty": "Spine Surgeon",
      "designation": " Senior Consultant",
      "hospital": NaN,
      "city": "New Delhi, India",
      "experience": "32+",
      "image": "https://d1ea147o02h74h.cloudfront.net/image-removebg-preview46-min.png",
      "path": "/doctors/dr-rajagopalan-krishnan"
    },
    {
      "id": 111,
      "name": "Dr. Rahul Bhargava",
      "specialty": "Hematologist",
      "designation": " Director",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "24+",
      "image": "https://www.vaidam.com/sites/default/files/dr_rahul_bhargava.jpg",
      "path": "/doctors/dr-rahul-bhargava"
    },
    {
      "id": 112,
      "name": "Dr. Raghuram Sekhar",
      "specialty": "Endovascular Surgeon",
      "designation": " Consultant",
      "hospital": "Kokilaben Dhirubhai Ambani Hospital, Mumbai",
      "city": "Mumbai, India",
      "experience": "33+",
      "image": "https://www.vaidam.com/sites/default/files/dr._raghuram_sekhar-min.png",
      "path": "/doctors/dr-raghuram-sekhar"
    },
    {
      "id": 113,
      "name": "Dr. Puneet Girdhar",
      "specialty": "Spine Surgeon",
      "designation": " Head of Department",
      "hospital": "BLK-Max Super Speciality Hospital Delhi",
      "city": "New Delhi, India",
      "experience": "26+",
      "image": "https://www.vaidam.com/sites/default/files/dr._puneet_girdhar.jpg",
      "path": "/doctors/dr-puneet-girdhar"
    },
    {
      "id": 114,
      "name": "Dr. Priyadarshan K",
      "specialty": "Aesthetics and Plastic Surgeon",
      "designation": " Consultant",
      "hospital": "Fortis Hospital, Bangalore (Bannerghatta Road)",
      "city": "Bangalore, India",
      "experience": "30+",
      "image": "https://d1ea147o02h74h.cloudfront.net/image-removebg-preview_64.png",
      "path": "/doctors/dr-priyadarshan-k"
    },
    {
      "id": 115,
      "name": "Dr. Prita Trehan",
      "specialty": "General Paediatrician",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "53+",
      "image": "https://www.vaidam.com/sites/default/files/dr._prita_trehan_1.jpg",
      "path": "/doctors/dr-prita-trehan"
    },
    {
      "id": 116,
      "name": "Dr. Pranathi Gutta",
      "specialty": "Paediatric Neurologist",
      "designation": " Consultant",
      "hospital": "Rainbow Children's Hospital and BirthRight by Rainbow, Kondapur, Hyderabad",
      "city": "Hyderabad, India",
      "experience": "23+",
      "image": "https://www.vaidam.com/sites/default/files/dr._pranathi_gutta.jpg",
      "path": "/doctors/dr-pranathi-gutta"
    },
    {
      "id": 117,
      "name": "Dr. Pranathi Gutta",
      "specialty": "Paediatric Neurologist",
      "designation": " Consultant",
      "hospital": "Rainbow Children's Hospital and BirthRight by Rainbow, Kondapur, Hyderabad",
      "city": "Hyderabad, India",
      "experience": "23+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._pranathi_gutta.jpg",
      "path": "/doctors/dr-pranathi-gutta"
    },
    {
      "id": 118,
      "name": "Dr. Pradeep Chowbey",
      "specialty": "Obesity and Bariatric Surgeon",
      "designation": " Chairman",
      "hospital": "Max Super Speciality Hospital, Saket, New Delhi",
      "city": "New Delhi, India",
      "experience": "42+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_pradeep_chowbey.jpg",
      "path": "/doctors/dr-pradeep-chowbey"
    },
    {
      "id": 119,
      "name": "Dr. Philomena Vaz",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Consultant",
      "hospital": "Manipal Hospital (Old Airport Road) Bangalore",
      "city": "Bangalore, India",
      "experience": "50+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._philomena_vaz.jpg",
      "path": "/doctors/dr-philomena-vaz"
    },
    {
      "id": 120,
      "name": "Dr. Pawan Rawal",
      "specialty": "Medical Gastroenterologist",
      "designation": " Head of Department",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "25+",
      "image": "https://www.vaidam.com/sites/default/files/dr._pawan_rawal-min.jpg",
      "path": "/doctors/dr-pawan-rawal"
    },
    {
      "id": 121,
      "name": "Dr. Parul Katiyar",
      "specialty": "Infertility Specialist",
      "designation": " Consultant",
      "hospital": "ART Fertility Clinics, Delhi",
      "city": "New Delhi, India",
      "experience": "22+",
      "image": "https://www.vaidam.com/sites/default/files/dr.-min_1.jpg",
      "path": "/doctors/dr-parul-katiyar"
    },
    {
      "id": 122,
      "name": "Dr. Parul Gupta Khanna",
      "specialty": "Infertility Specialist",
      "designation": " Consultant",
      "hospital": "Nova IVF Fertility, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "9+",
      "image": "https://www.vaidam.com/sites/default/files/dr._parul_gupta_1.png",
      "path": "/doctors/dr-parul-gupta-khanna"
    },
    {
      "id": 123,
      "name": "Dr. Pankaj Venkatrao Deshpande",
      "specialty": "Paediatric Nephrologist",
      "designation": " Consultant",
      "hospital": "Apollo Hospitals, Mumbai",
      "city": "Mumbai, India",
      "experience": "34+",
      "image": "https://d1ea147o02h74h.cloudfront.net/drpankaj_venkatrao_deshpande-min.jpg",
      "path": "/doctors/dr-pankaj-venkatrao-deshpande"
    },
    {
      "id": 124,
      "name": "Dr. Nutan Agarwal",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Head of Department",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "45+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._nutan_agarwal_-_obstetrician_and_gynecologist.jpg",
      "path": "/doctors/dr-nutan-agarwal"
    },
    {
      "id": 125,
      "name": "Dr. Nitin Sood",
      "specialty": "Hematologist",
      "designation": " Director",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "28+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._nitin_sood-min.jpeg",
      "path": "/doctors/dr-nitin-sood"
    },
    {
      "id": 126,
      "name": "Dr. Niranjan Naik",
      "specialty": "Surgical Oncologist",
      "designation": " Consultant",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "31+",
      "image": "https://www.vaidam.com/sites/default/files/dr._niranjan_naik-removebg-preview-min.png",
      "path": "/doctors/dr-niranjan-naik"
    },
    {
      "id": 127,
      "name": "Dr. Neville Solomon",
      "specialty": "Pediatric Cardiac Surgeon",
      "designation": " Consultant",
      "hospital": "Apollo Children's Hospital, Chennai",
      "city": "Chennai, India",
      "experience": "27+",
      "image": "https://www.vaidam.com/sites/default/files/dr._neville_solomon-min.jpg",
      "path": "/doctors/dr-neville-solomon"
    },
    {
      "id": 128,
      "name": "Dr. Neha Gupta",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Senior Consultant",
      "hospital": "Mediworld IVF Center and Fertility",
      "city": "New Delhi, India",
      "experience": "19+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_neha_gupta.jpg",
      "path": "/doctors/dr-neha-gupta"
    },
    {
      "id": 129,
      "name": "Dr. Neeraj Awasthy",
      "specialty": "Pediatric Cardiologist",
      "designation": " Director",
      "hospital": "Fortis Escorts Heart Institute, New Delhi",
      "city": "New Delhi, India",
      "experience": "25+",
      "image": "https://www.vaidam.com/sites/default/files/dr._neeraj_awasthy.jpg",
      "path": "/doctors/dr-neeraj-awasthy"
    },
    {
      "id": 130,
      "name": "Dr. Naveen Bhamri",
      "specialty": "Interventional Cardiologist",
      "designation": " Consultant",
      "hospital": "Max Super Speciality hospital, Shalimar Bagh, New Delhi",
      "city": "New Delhi, India",
      "experience": "23+",
      "image": "https://www.vaidam.com/sites/default/files/dr-naveen-bhamri-cardiology.jpg",
      "path": "/doctors/dr-naveen-bhamri"
    },
    {
      "id": 131,
      "name": "Dr. Nagraj Gururaj Huilgol",
      "specialty": "Radiation Oncologist",
      "designation": " Consultant",
      "hospital": "Nanavati Super Specialty Hospital, Mumbai",
      "city": "Mumbai, India",
      "experience": "47+",
      "image": "https://www.vaidam.com/sites/default/files/dr._nagraj_gururaj_huilgol.jpg",
      "path": "/doctors/dr-nagraj-gururaj-huilgol"
    },
    {
      "id": 132,
      "name": "Dr. N. Ragavan",
      "specialty": "Endourologist",
      "designation": " Consultant",
      "hospital": "Apollo Hospitals, Greams Road, Chennai",
      "city": "Chennai, India",
      "experience": "32+",
      "image": "https://www.vaidam.com/sites/default/files/dr._n._ragavan.jpg",
      "path": "/doctors/dr-n-ragavan"
    },
    {
      "id": 133,
      "name": "Dr. Murugan N",
      "specialty": "Hepato-Pancreato-Biliary Surgeon",
      "designation": " Consultant",
      "hospital": "Apollo Hospitals, Greams Road, Chennai",
      "city": "Chennai, India",
      "experience": "46+",
      "image": "https://www.vaidam.com/sites/default/files/dr-murugan-n.jpg",
      "path": "/doctors/dr-murugan-n"
    },
    {
      "id": 134,
      "name": "Dr. Mukut Minz",
      "specialty": "Urologist and Renal Transplant Specialist",
      "designation": " Director",
      "hospital": "Fortis Hospital, Mohali",
      "city": "Mohali, India",
      "experience": "48+",
      "image": "https://www.vaidam.com/sites/default/files/dr._mukut_minz_-_urologist_and_renal_transplant_surgeon.jpg",
      "path": "/doctors/dr-mukut-minz"
    },
    {
      "id": 135,
      "name": "Dr. Mriganka Sekhar Sharma",
      "specialty": "Advanced Laparoscopic, Minimal Access and Bariatric Surgeon",
      "designation": " Chief",
      "hospital": "Manipal Hospital Formerly Columbia Asia, Palam Vihar, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "30+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr_mrigankar_sekar_sharma.jpg",
      "path": "/doctors/dr-mriganka-sekhar-sharma"
    },
    {
      "id": 136,
      "name": "Dr. Moorthy G",
      "specialty": "Pediatric Urologist",
      "designation": " Senior Consultant",
      "hospital": "Rainbow Children's Hospital & BirthRight by Rainbow, Chennai",
      "city": "Chennai, India",
      "experience": "14+",
      "image": "https://www.vaidam.com/sites/default/files/dr._moorthy_g-min.jpg",
      "path": "/doctors/dr-moorthy-g"
    },
    {
      "id": 137,
      "name": "Dr. Meenakshi Dua",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Senior Consultant",
      "hospital": "ART Fertility Clinics, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "26+",
      "image": "https://www.vaidam.com/sites/default/files/dr._meenakshi_dua-removebg-preview-min.png",
      "path": "/doctors/dr-meenakshi-dua"
    },
    {
      "id": 138,
      "name": "Dr Manvinder Singh Sachdev",
      "specialty": "Pediatric Cardiologist",
      "designation": " Consultant",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "28+",
      "image": "https://www.vaidam.com/sites/default/files/dr._manvinder-min.jpg",
      "path": "/doctors/dr-manvinder-singh-sachdev"
    },
    {
      "id": 139,
      "name": "Dr. Manoj Miglani",
      "specialty": "Spine Surgeon",
      "designation": " Director",
      "hospital": "Fortis Flt. Lt. Rajan Dhall Hospital, Vasant Kunj, New Delhi",
      "city": "New Delhi, India",
      "experience": "27+",
      "image": "https://www.vaidam.com/sites/default/files/dr._manoj_miglani_-_orthopedics_and_joint_replacement_surgeon.jpg",
      "path": "/doctors/dr-manoj-miglani"
    },
    {
      "id": 140,
      "name": "Dr. Manju Sinha",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Senior Consultant",
      "hospital": "Fortis Hospital, Noida",
      "city": "Noida, India",
      "experience": "52+",
      "image": "https://www.vaidam.com/sites/default/files/dr._manju_sinha.jpg",
      "path": "/doctors/dr-manju-sinha"
    },
    {
      "id": 141,
      "name": "Dr. Madan Mohan Reddy",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Senior Consultant",
      "hospital": "Apollo Hospitals, Greams Road, Chennai",
      "city": "Chennai, India",
      "experience": "35+",
      "image": "https://www.vaidam.com/sites/default/files/dr._madan_mohan_reddy-min.jpg",
      "path": "/doctors/dr-madan-mohan-reddy"
    },
    {
      "id": 142,
      "name": "Dr. Lavi Sindhu",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Consultant",
      "hospital": "Birla Fertility and IVF Center, Lajpat Nagar",
      "city": "New Delhi, India",
      "experience": "14+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._lavi-min.jpg",
      "path": "/doctors/dr-lavi-sindhu"
    },
    {
      "id": 143,
      "name": "Dr. Lakshmi Kant Tripathi",
      "specialty": "Nephrologist",
      "designation": " Senior Consultant",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "31+",
      "image": "https://www.vaidam.com/sites/default/files/dr._lakshmi_kant_tripathi.jpg",
      "path": "/doctors/dr-lakshmi-kant-tripathi"
    },
    {
      "id": 144,
      "name": "Dr. Kulbhushan Singh Dagar",
      "specialty": "Cardiac Surgeon",
      "designation": " Director",
      "hospital": "Max Super Speciality Hospital, Saket, New Delhi",
      "city": "New Delhi, India",
      "experience": "36+",
      "image": "https://www.vaidam.com/sites/default/files/dr._kulbhushan_singh_dagar.jpg",
      "path": "/doctors/dr-kulbhushan-singh-dagar"
    },
    {
      "id": 145,
      "name": "Dr. Kulbhushan Singh Dagar",
      "specialty": "Cardiac Surgeon",
      "designation": " Director",
      "hospital": "Max Super Speciality Hospital, Saket, New Delhi",
      "city": "New Delhi, India",
      "experience": "36+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._kulbhushan_singh_dagar.jpg",
      "path": "/doctors/dr-kulbhushan-singh-dagar"
    },
    {
      "id": 146,
      "name": "Dr. Krishna S Iyer",
      "specialty": "Pediatric Cardiac Surgeon",
      "designation": " Director",
      "hospital": "Fortis Escorts Heart Institute, New Delhi",
      "city": "New Delhi, India",
      "experience": "46+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr._krishna_s_iyer-min_0.webp",
      "path": "/doctors/dr-krishna-s-iyer"
    },
    {
      "id": 147,
      "name": "Dr. Kokkula Praneeth",
      "specialty": "Neurosurgeon",
      "designation": " Consultant",
      "hospital": "Rainbow Children's Hospital and BirthRight by Rainbow, Hyderabad",
      "city": "Hyderabad, India",
      "experience": "15+",
      "image": "https://www.vaidam.com/sites/default/files/dr._kokkula_praneeth-min.png",
      "path": "/doctors/dr-kokkula-praneeth"
    },
    {
      "id": 148,
      "name": "Dr Keshava R",
      "specialty": "Interventional Cardiologist",
      "designation": " Director",
      "hospital": "Fortis Hospital, Bangalore (Cunningham Road)",
      "city": "Bangalore, India",
      "experience": "38+",
      "image": "https://www.vaidam.com/sites/default/files/untitled339-min.png",
      "path": "/doctors/dr-keshava-r"
    },
    {
      "id": 149,
      "name": "Dr. Kaustubh Patel",
      "specialty": "Surgical Oncologist",
      "designation": " Senior Consultant",
      "hospital": "HCG Cancer Centre, Ahmedabad",
      "city": "Ahmedabad, India",
      "experience": "50+",
      "image": "https://www.vaidam.com/sites/default/files/dr-kaustubh-patel.jpg",
      "path": "/doctors/dr-kaustubh-patel"
    },
    {
      "id": 150,
      "name": "Dr. Kapil Kumar",
      "specialty": "Surgical Oncologist",
      "designation": " Director",
      "hospital": "Fortis Hospital, Shalimar Bagh, New Delhi",
      "city": "New Delhi, India",
      "experience": "40+",
      "image": "https://www.vaidam.com/sites/default/files/dr.-kapil-kumar.jpg",
      "path": "/doctors/dr-kapil-kumar"
    },
    {
      "id": 151,
      "name": "Dr. KNK Shetty",
      "specialty": "Medical Gastroenterologist",
      "designation": " Consultant",
      "hospital": "Manipal Hospital (Old Airport Road) Bangalore",
      "city": "Bangalore, India",
      "experience": "48+",
      "image": "https://www.vaidam.com/sites/default/files/dr._knk_shetty.jpg",
      "path": "/doctors/dr-knk-shetty"
    },
    {
      "id": 152,
      "name": "Dr. K.N. Srivastava",
      "specialty": "General Surgeon",
      "designation": " HOD",
      "hospital": "BLK-Max Super Speciality Hospital Delhi",
      "city": "New Delhi, India",
      "experience": "52+",
      "image": "https://www.vaidam.com/sites/default/files/dr._kn-min.jpg",
      "path": "/doctors/dr-kn-srivastava"
    },
    {
      "id": 153,
      "name": "Dr. K.N. Srivastava",
      "specialty": "General Surgeon",
      "designation": " HOD",
      "hospital": "BLK-Max Super Speciality Hospital Delhi",
      "city": "New Delhi, India",
      "experience": "52+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._kn-min.jpg",
      "path": "/doctors/dr-kn-srivastava"
    },
    {
      "id": 154,
      "name": "Dr. Jyoti Anant Bobe",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Consultant",
      "hospital": "Apollo Hospitals, Mumbai",
      "city": "Mumbai, India",
      "experience": "32+",
      "image": "https://d1ea147o02h74h.cloudfront.net/jyoti_anant_bobe-min.jpg",
      "path": "/doctors/dr-jyoti-anant-bobe"
    },
    {
      "id": 155,
      "name": "Dr. Jayesh Sardhara",
      "specialty": "Neurosurgeon",
      "designation": " Senior Consultant",
      "hospital": "Fortis Hospital, Mulund, Mumbai",
      "city": "Mumbai, India",
      "experience": "15+",
      "image": "https://www.vaidam.com/sites/default/files/dr._jayesh_sardhara.jpg",
      "path": "/doctors/dr-jayesh-sardhara"
    },
    {
      "id": 156,
      "name": "Dr. Jayant Arora",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Director",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "29+",
      "image": "https://www.vaidam.com/sites/default/files/dr_jayant_arora-min.png",
      "path": "/doctors/dr-jayant-arora"
    },
    {
      "id": 157,
      "name": "Dr. Jai Dev Wig",
      "specialty": "Surgical Oncologist",
      "designation": " Director",
      "hospital": "Fortis Hospital, Mohali",
      "city": "Mohali, India",
      "experience": "44+",
      "image": "https://www.vaidam.com/sites/default/files/dr_jai.jpg",
      "path": "/doctors/dr-jai-dev-wig"
    },
    {
      "id": 158,
      "name": "Dr. IPS Oberoi",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Chairman",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "31+",
      "image": "https://www.vaidam.com/sites/default/files/dr._ips_oberoi_-_orthopaedics-min.jpg",
      "path": "/doctors/dr-ips-oberoi"
    },
    {
      "id": 159,
      "name": "Dr. I. P. S. Kochar",
      "specialty": "Endocrinologist",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "Noida, India",
      "experience": "40+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._i.p.s._kochar.jpg",
      "path": "/doctors/dr-i-p-s-kochar"
    },
    {
      "id": 160,
      "name": "Dr. Hitesh Garg",
      "specialty": "Spine Surgeon",
      "designation": " HOD",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "23+",
      "image": "https://www.vaidam.com/sites/default/files/dr._hitesh_garg_-_orthopaedics_spine_surgeon-min.jpg",
      "path": "/doctors/dr-hitesh-garg"
    },
    {
      "id": 161,
      "name": "Dr. Hemant Sharma",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Chairman",
      "hospital": "Marengo Asia Hospitals Formerly W Pratiksha Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "29+",
      "image": "https://www.vaidam.com/sites/default/files/dr._hemant_sharma_-_orthopedist.jpg",
      "path": "/doctors/dr-hemant-sharma"
    },
    {
      "id": 162,
      "name": "Dr. Harshavardhan Hegde",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Director",
      "hospital": "Max Super Speciality Hospital, Saket, New Delhi",
      "city": "New Delhi, India",
      "experience": "42+",
      "image": "https://www.vaidam.com/sites/default/files/dr._harshavardhan_hegde-min.png",
      "path": "/doctors/dr-harshavardhan-hegde"
    },
    {
      "id": 163,
      "name": "Dr. Harnarayan Singh",
      "specialty": "Neurosurgeon",
      "designation": " Consultant",
      "hospital": "Sanar International Hospital",
      "city": "Gurgaon, India",
      "experience": "18+",
      "image": "https://www.vaidam.com/sites/default/files/1656409520_dr.-harnarayan-singh-2.jpg",
      "path": "/doctors/dr-harnarayan-singh"
    },
    {
      "id": 164,
      "name": "Dr Hari Goyal",
      "specialty": "Medical Oncologist",
      "designation": " HOD",
      "hospital": "BLK-Max Super Speciality Hospital Delhi",
      "city": "New Delhi, India",
      "experience": "29+",
      "image": "https://www.vaidam.com/sites/default/files/dr_hari_goyal-min.jpg",
      "path": "/doctors/dr-hari-goyal"
    },
    {
      "id": 165,
      "name": "Dr. H. S. Bhatyal",
      "specialty": "Urologist",
      "designation": " Senior Consultant",
      "hospital": "BLK-Max Super Speciality Hospital Delhi",
      "city": "New Delhi, India",
      "experience": "53+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr-h-s-bhatyal-urology.jpg",
      "path": "/doctors/dr-h-s-bhatyal"
    },
    {
      "id": 166,
      "name": "Dr. Giriraj Bora",
      "specialty": "Surgical Gastroenterologist",
      "designation": " Additional Director",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "28+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._giriraj_bora-min.jpg",
      "path": "/doctors/dr-giriraj-bora"
    },
    {
      "id": 167,
      "name": "Dr. Gaurav Kharya",
      "specialty": "Hematologist",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "24+",
      "image": "https://www.vaidam.com/sites/default/files/dr_gaurav_kharya.jpeg",
      "path": "/doctors/dr-gaurav-kharya"
    },
    {
      "id": 168,
      "name": "Dr. G. Balamurali",
      "specialty": "Spine Surgeon",
      "designation": " HOD",
      "hospital": "Kauvery Hospital, Alwarpet",
      "city": "Chennai, India",
      "experience": "26+",
      "image": "https://www.vaidam.com/sites/default/files/dr._g._balamurali-min.jpg",
      "path": "/doctors/dr-g-balamurali"
    },
    {
      "id": 169,
      "name": "Dr. Dinesh Kansal",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Head of Department",
      "hospital": "BLK-Max Super Speciality Hospital Delhi",
      "city": "New Delhi, India",
      "experience": "45+",
      "image": "https://www.vaidam.com/sites/default/files/dr._dinesh_kansal_gynecology_0.jpg",
      "path": "/doctors/dr-dinesh-kansal"
    },
    {
      "id": 170,
      "name": "Dr. Deepak Govil",
      "specialty": "Surgical Gastroenterologist",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "42+",
      "image": "https://www.vaidam.com/sites/default/files/dr._deepak_govil-removebg-preview-min_1.png",
      "path": "/doctors/dr-deepak-govil"
    },
    {
      "id": 171,
      "name": "Dr. Deepak Dubey",
      "specialty": "Urologist and Renal Transplant Specialist",
      "designation": " Consultant",
      "hospital": "Manipal Hospital (Old Airport Road) Bangalore",
      "city": "Bangalore, India",
      "experience": "30+",
      "image": "https://www.vaidam.com/sites/default/files/dr._deepak_dubey-removebg-preview-min.png",
      "path": "/doctors/dr-deepak-dubey"
    },
    {
      "id": 172,
      "name": "Dr. D. K.Agarwal",
      "specialty": "Nephrologist",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "40+",
      "image": "https://www.vaidam.com/sites/default/files/dr._d._k.agarwal-min.jpg",
      "path": "/doctors/dr-d-kagarwal"
    },
    {
      "id": 173,
      "name": "Dr. Brahm Datt Pathak",
      "specialty": "Advanced Laparoscopic, Minimal Access and Bariatric Surgeon",
      "designation": " Director",
      "hospital": "Fortis Escorts Hospital, Faridabad",
      "city": "Faridabad, India",
      "experience": "34+",
      "image": "https://www.vaidam.com/sites/default/files/patak.jpg",
      "path": "/doctors/dr-brahm-datt-pathak"
    },
    {
      "id": 174,
      "name": "Dr. Bipin Walia",
      "specialty": "Spine Surgeon",
      "designation": " Director",
      "hospital": "Max Super Speciality Hospital, Saket, New Delhi",
      "city": "New Delhi, India",
      "experience": "41+",
      "image": "https://www.vaidam.com/sites/default/files/dr._bipin_s._walia.jpg",
      "path": "/doctors/dr-bipin-walia"
    },
    {
      "id": 175,
      "name": "Dr. Bindu Garg",
      "specialty": "Infertility Specialist",
      "designation": " Chairman",
      "hospital": "Neelkanth Hospitals, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "44+",
      "image": "https://www.vaidam.com/sites/default/files/dr._bindu_garg-min.jpg",
      "path": "/doctors/dr-bindu-garg"
    },
    {
      "id": 176,
      "name": "Dr. Bhushan Nariani",
      "specialty": "Orthopaedic and Joint Replacement Surgeon",
      "designation": " Chairman",
      "hospital": "BLK-Max Super Speciality Hospital Delhi",
      "city": "New Delhi, India",
      "experience": "25+",
      "image": "https://www.vaidam.com/sites/default/files/dr._bhushan_nariani.jpg",
      "path": "/doctors/dr-bhushan-nariani"
    },
    {
      "id": 177,
      "name": "Dr. Bhaba Nanda Das",
      "specialty": "Cardiac Surgeon",
      "designation": " Chief",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "47+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr_bhaba_nanda_das-min.webp",
      "path": "/doctors/dr-bhaba-nanda-das"
    },
    {
      "id": 178,
      "name": "Dr. Bhaba Nanda Das",
      "specialty": "Cardiac Surgeon",
      "designation": " Chief",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "47+",
      "image": "https://www.vaidam.com/sites/default/files/dr_bhaba_nanda_das-min.jpg",
      "path": "/doctors/dr-bhaba-nanda-das"
    },
    {
      "id": 179,
      "name": "Dr. B M L Kapoor",
      "specialty": "Colo-Rectal Surgeon",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "10+",
      "image": "https://www.vaidam.com/sites/default/files/7_61.jpg",
      "path": "/doctors/dr-b-m-l-kapoor"
    },
    {
      "id": 180,
      "name": "Dr. Atul Sharma Joshi",
      "specialty": "Advanced Laparoscopic, Minimal Access and Bariatric Surgeon",
      "designation": " Associate Director",
      "hospital": "Fortis Hospital, Mohali",
      "city": "Mohali, India",
      "experience": "34+",
      "image": "https://www.vaidam.com/sites/default/files/dr_atul.png",
      "path": "/doctors/dr-atul-sharma-joshi"
    },
    {
      "id": 181,
      "name": "Dr. Ashutosh Marwah",
      "specialty": "Pediatric Cardiac Surgeon",
      "designation": " Director",
      "hospital": "Fortis Escorts Heart Institute, New Delhi",
      "city": "New Delhi, India",
      "experience": "34+",
      "image": "https://www.vaidam.com/sites/default/files/dr._ashutosh_marwah.jpg",
      "path": "/doctors/dr-ashutosh-marwah"
    },
    {
      "id": 182,
      "name": "Dr. Ashok Sarin",
      "specialty": "Nephrologist",
      "designation": " Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "55+",
      "image": "https://www.vaidam.com/sites/default/files/dr._ashok_sarin-min.png",
      "path": "/doctors/dr-ashok-sarin"
    },
    {
      "id": 183,
      "name": "Dr. Ashok Vaid",
      "specialty": "Medical Oncologist",
      "designation": " Consultant",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "41+",
      "image": "https://www.vaidam.com/sites/default/files/dr._ashok_vaid_-_medical_oncologist-min.jpg",
      "path": "/doctors/dr-ashok-vaid"
    },
    {
      "id": 184,
      "name": "Dr. Ashish Sabharwal",
      "specialty": "Urologist",
      "designation": " Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "24+",
      "image": "https://www.vaidam.com/sites/default/files/dr_ashish_sabharwal.jpg",
      "path": "/doctors/dr-ashish-sabharwal"
    },
    {
      "id": 185,
      "name": "Dr. Ashish Dixit",
      "specialty": "Hematologist",
      "designation": " Consultant",
      "hospital": "Manipal Hospital (Old Airport Road) Bangalore",
      "city": "Bangalore, India",
      "experience": "30+",
      "image": "https://www.vaidam.com/sites/default/files/aashish_dixit_1.jpeg",
      "path": "/doctors/dr-ashish-dixit"
    },
    {
      "id": 186,
      "name": "Dr. Asheesh Sharma",
      "specialty": "General Surgeon",
      "designation": " Senior Consultant",
      "hospital": "Apollo Medics Super Speciality Hospital, Lucknow",
      "city": "Lucknow, India",
      "experience": "29+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._asheesh_sharma-min.jpg",
      "path": "/doctors/dr-asheesh-sharma"
    },
    {
      "id": 187,
      "name": "Dr. Arvinder Singh Soin",
      "specialty": "Liver Transplant Surgeon",
      "designation": " Chairman",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "38+",
      "image": "https://www.vaidam.com/sites/default/files/dr._arvinder_singh_soin-removebg-preview-min.png",
      "path": "/doctors/dr-arvinder-singh-soin"
    },
    {
      "id": 188,
      "name": "Dr. Arvind Khurana",
      "specialty": "Medical Gastroenterologist",
      "designation": " Director",
      "hospital": "Fortis Memorial Research Institute, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "39+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr._arvind_khurana-min.webp",
      "path": "/doctors/dr-arvind-khurana"
    },
    {
      "id": 189,
      "name": "Dr. Aruna Kalra",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Director",
      "hospital": "CK Birla Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "28+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr_aruna_kalra.webp",
      "path": "/doctors/dr-aruna-kalra"
    },
    {
      "id": 190,
      "name": "Dr. Arun Halankar",
      "specialty": "Nephrologist",
      "designation": " Consultant",
      "hospital": "Jaslok Hospital, Mumbai",
      "city": "Mumbai, India",
      "experience": "57+",
      "image": "https://d1ea147o02h74h.cloudfront.net/image-removebg-preview42-min.png",
      "path": "/doctors/dr-arun-halankar"
    },
    {
      "id": 191,
      "name": "Dr. Anupam Jindal",
      "specialty": "Neurosurgeon",
      "designation": " Additional Director",
      "hospital": "Fortis Hospital, Mohali",
      "city": "Mohali, India",
      "experience": "25+",
      "image": "https://www.vaidam.com/sites/default/files/dr._anupam_jindal-min.jpg",
      "path": "/doctors/dr-anupam-jindal"
    },
    {
      "id": 192,
      "name": "Dr. Anjila Aneja",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Director",
      "hospital": "Fortis La Femme, New Delhi",
      "city": "New Delhi, India",
      "experience": "37+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._anjila_aneja-min_1.jpg",
      "path": "/doctors/dr-anjila-aneja"
    },
    {
      "id": 193,
      "name": "Dr. Anjali Kumar",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Head of Department",
      "hospital": "CK Birla Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "37+",
      "image": "https://www.vaidam.com/sites/default/files/dr-anjali-kumar-obstetrics-gynecologist.jpg",
      "path": "/doctors/dr-anjali-kumar"
    },
    {
      "id": 194,
      "name": "Dr. Anil Bhan",
      "specialty": "Cardiac Surgeon",
      "designation": " Chairman",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "49+",
      "image": "https://www.vaidam.com/sites/default/webp/50/files/dr_anil_bhan-min.webp",
      "path": "/doctors/dr-anil-bhan"
    },
    {
      "id": 195,
      "name": "Dr. Anil Bhan",
      "specialty": "Cardiac Surgeon",
      "designation": " Chairman",
      "hospital": "Medanta - The Medicity, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "49+",
      "image": "https://www.vaidam.com/sites/default/files/dr_anil_bhan-min.jpg",
      "path": "/doctors/dr-anil-bhan"
    },
    {
      "id": 196,
      "name": "Dr. Amitabha Ghosh",
      "specialty": "Laparoscopic Surgeon",
      "designation": " Consultant",
      "hospital": "Manipal Hospital Formerly AMRI Hospital, Kolkata (Dhakuria)",
      "city": "Kolkata, India",
      "experience": "31+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._amitabha_ghosh-removebg-preview-min.png",
      "path": "/doctors/dr-amitabha-ghosh"
    },
    {
      "id": 197,
      "name": "Dr. Alka Kriplani",
      "specialty": "Gynaecologist and Obstetrician",
      "designation": " Head of Department",
      "hospital": "Paras Hospitals, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "44+",
      "image": "https://www.vaidam.com/sites/default/files/dr._alka_kriplani_-_gynecologist_and_fertility_expert.jpg",
      "path": "/doctors/dr-alka-kriplani"
    },
    {
      "id": 198,
      "name": "Dr. Akhil Mishra",
      "specialty": "Nephrologist",
      "designation": " Senior Consultant",
      "hospital": "Indraprastha Apollo Hospital, New Delhi",
      "city": "New Delhi, India",
      "experience": "59+",
      "image": "https://www.vaidam.com/sites/default/files/dr._akhil_mishra-min.jpg",
      "path": "/doctors/dr-akhil-mishra"
    },
    {
      "id": 199,
      "name": "Dr. Akhil Govil",
      "specialty": "Cardiac Surgeon",
      "designation": " Senior Consultant",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "29+",
      "image": "https://www.vaidam.com/sites/default/files/dr._akhil_govil_0.jpg",
      "path": "/doctors/dr-akhil-govil"
    },
    {
      "id": 200,
      "name": "Dr. Akhil Govil",
      "specialty": "Cardiac Surgeon",
      "designation": " Senior Consultant",
      "hospital": "Artemis Hospital, Gurgaon",
      "city": "Gurgaon, India",
      "experience": "29+",
      "image": "https://d1ea147o02h74h.cloudfront.net/dr._akhil_govil_0.jpg",
      "path": "/doctors/dr-akhil-govil"
    }
  ]